In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("googleplaystore - googleplaystore (1).csv")

In [4]:
df.sample(10)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
3254,"Calculator - free calculator ,multi calculator...",TOOLS,4.4,1236,5.8M,"100,000+",Free,0,Everyone,Tools,"July 6, 2018",8.1.6,4.2 and up
5479,iScore5 AP Psych,FAMILY,2.9,10,73M,100+,Paid,$4.99,Everyone,Educational,"April 25, 2017",2,4.0.3 and up
1291,The TK-App - everything under control,HEALTH_AND_FITNESS,4.5,8642,18M,"100,000+",Free,0,Everyone,Health & Fitness,"August 2, 2018",1.2,4.4 and up
10750,Finger Scanner Gestures,TOOLS,4.2,2531,3.3M,"100,000+",Free,0,Everyone,Tools,"July 30, 2017",1.2.4,6.0 and up
1153,NetSpend Prepaid,FINANCE,4.2,15993,45M,"1,000,000+",Free,0,Everyone,Finance,"May 9, 2018",4.10.0,4.4 and up
3155,TravelPirates,TRAVEL_AND_LOCAL,4.8,43054,Varies with device,"1,000,000+",Free,0,Everyone,Travel & Local,"August 6, 2018",Varies with device,Varies with device
3811,CNN Breaking US & World News,NEWS_AND_MAGAZINES,4.0,293080,25M,"10,000,000+",Free,0,Everyone 10+,News & Magazines,"August 6, 2018",5.17,4.4 and up
5899,Oxford A-Z of English Usage,BOOKS_AND_REFERENCE,4.0,5300,11M,"1,000,000+",Free,0,Everyone,Books & Reference,"November 28, 2017",9.1.284,4.1 and up
1185,Frigo Magic: Easy recipe idea and anti-waste,FOOD_AND_DRINK,4.1,2473,14M,"500,000+",Free,0,Everyone,Food & Drink,"July 28, 2018",3.1.5,4.4 and up
2838,Kids Photo Frames,PHOTOGRAPHY,4.6,15700,10M,"1,000,000+",Free,0,Everyone,Photography,"July 7, 2018",2.3,4.0.3 and up

In [5]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [11]:
df.tail()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [13]:
df.shape

(10841, 13)

In [14]:
df.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='object')

In [15]:
df.info

<bound method DataFrame.info of                                                      App             Category  \
0         Photo Editor & Candy Camera & Grid & ScrapBook       ART_AND_DESIGN
1                                    Coloring book moana       ART_AND_DESIGN
2      U Launcher Lite – FREE Live Cool Themes, Hide ...       ART_AND_DESIGN
3                                  Sketch - Draw & Paint       ART_AND_DESIGN
4                  Pixel Draw - Number Art Coloring Book       ART_AND_DESIGN
...                                                  ...                  ...
10836                                   Sya9a Maroc - FR               FAMILY
10837                   Fr. Mike Schmitz Audio Teachings               FAMILY
10838                             Parkinson Exercices FR              MEDICAL
10839                      The SCP Foundation DB fr nn5n  BOOKS_AND_REFERENCE
10840      iHoroscope - 2018 Daily Horoscope & Astrology            LIFESTYLE

       Rating Reviews                Size     Installs  Type Price  \
0         4.1     159                 19M      10,000+  Free     0
1         3.9     967                 14M     500,000+  Free     0
2         4.7   87510                8.7M   5,000,000+  Free     0
3         4.5  215644                 25M  50,000,000+  Free     0
4         4.3     967                2.8M     100,000+  Free     0
...       ...     ...                 ...          ...   ...   ...
10836     4.5      38                 53M       5,000+  Free     0
10837     5.0       4                3.6M         100+  Free     0
10838     NaN       3                9.5M       1,000+  Free     0
10839     4.5     114  Varies with device       1,000+  Free     0
10840     4.5  398307                 19M  10,000,000+  Free     0

      Content Rating                     Genres      Last Updated  \
0           Everyone               Art & Design   January 7, 2018
1           Everyone  Art & Design;Pretend Play  January 15, 2018
2           Everyone               Art & Design    August 1, 2018
3               Teen               Art & Design      June 8, 2018
4           Everyone    Art & Design;Creativity     June 20, 2018
...              ...                        ...               ...
10836       Everyone                  Education     July 25, 2017
10837       Everyone                  Education      July 6, 2018
10838       Everyone                    Medical  January 20, 2017
10839     Mature 17+          Books & Reference  January 19, 2015
10840       Everyone                  Lifestyle     July 25, 2018

              Current Ver         Android Ver
0                   1.0.0        4.0.3 and up
1                   2.0.0        4.0.3 and up
2                   1.2.4        4.0.3 and up
3      Varies with device          4.2 and up
4                     1.1          4.4 and up
...                   ...                 ...
10836                1.48          4.1 and up
10837                   1          4.1 and up
10838                   1          2.2 and up
10839  Varies with device  Varies with device
10840  Varies with device  Varies with device

[10841 rows x 13 columns]>

In [16]:
df.dtypes

App                object
Category           object
Rating            float64
Reviews            object
Size               object
Installs           object
Type               object
Price              object
Content Rating     object
Genres             object
Last Updated       object
Current Ver        object
Android Ver        object
dtype: object

In [17]:
df.isnull().sum()

App                  0
Category             0
Rating            1474
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       1
Genres               0
Last Updated         0
Current Ver          8
Android Ver          3
dtype: int64

In [97]:
df.duplicated().sum()

np.int64(0)

In [102]:
duplicate=df[df.duplicated()]

In [103]:
duplicate

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
229,Quick PDF Scanner + OCR FREE,BUSINESS,4.2,80805,Varies with device,"5,000,000+",Free,0,Everyone,Business,"February 26, 2018",Varies with device,4.0.3 and up
236,Box,BUSINESS,4.2,159872,Varies with device,"10,000,000+",Free,0,Everyone,Business,"July 31, 2018",Varies with device,Varies with device
239,Google My Business,BUSINESS,4.4,70991,Varies with device,"5,000,000+",Free,0,Everyone,Business,"July 24, 2018",2.19.0.204537701,4.4 and up
256,ZOOM Cloud Meetings,BUSINESS,4.4,31614,37M,"10,000,000+",Free,0,Everyone,Business,"July 20, 2018",4.1.28165.0716,4.0 and up
261,join.me - Simple Meetings,BUSINESS,4.0,6989,Varies with device,"1,000,000+",Free,0,Everyone,Business,"July 16, 2018",4.3.0.508,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8643,Wunderlist: To-Do List & Tasks,PRODUCTIVITY,4.6,404610,Varies with device,"10,000,000+",Free,0,Everyone,Productivity,"April 6, 2018",Varies with device,Varies with device
8654,"TickTick: To Do List with Reminder, Day Planner",PRODUCTIVITY,4.6,25370,Varies with device,"1,000,000+",Free,0,Everyone,Productivity,"August 6, 2018",Varies with device,Varies with device
8658,ColorNote Notepad Notes,PRODUCTIVITY,4.6,2401017,Varies with device,"100,000,000+",Free,0,Everyone,Productivity,"June 27, 2018",Varies with device,Varies with device
10049,Airway Ex - Intubate. Anesthetize. Train.,MEDICAL,4.3,123,86M,"10,000+",Free,0,Everyone,Medical,"June 1, 2018",0.6.88,5.0 and up
10768,AAFP,MEDICAL,3.8,63,24M,"10,000+",Free,0,Everyone,Medical,"June 22, 2018",2.3.1,5.0 and up

In [104]:
df=df.drop_duplicates()

In [105]:
df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [115]:
duplicate.sort_values(by="Rating")

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
554,Just She - Top Lesbian Dating,DATING,1.9,953,19M,"100,000+",Free,0,Mature 17+,Dating,"July 18, 2018",6.3.7,5.0 and up
549,EliteSingles – Dating for Single Professionals,DATING,2.5,5377,19M,"500,000+",Free,0,Mature 17+,Dating,"July 31, 2018",4.8.5,4.0.3 and up
5958,Anthem BC Anywhere,MEDICAL,2.6,496,24M,"100,000+",Free,0,Everyone,Medical,"July 27, 2018",8.0.226,4.4 and up
678,MouseMingle,DATING,2.7,3,3.9M,100+,Free,0,Mature 17+,Dating,"July 17, 2018",1.0.0,4.4 and up
2517,Anthem Anywhere,MEDICAL,2.7,2657,24M,"500,000+",Free,0,Everyone,Medical,"July 27, 2018",8.0.226,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2502,Free Blood Pressure,MEDICAL,NaN,7,5.7M,"5,000+",Free,0,Everyone,Medical,"October 13, 2016",3.0.0,4.0.3 and up
2516,RT 516 VET,MEDICAL,NaN,0,29M,10+,Free,0,Everyone,Medical,"July 13, 2018",300000.1.11,4.0.3 and up
2529,Breastfeeding Tracker Baby Log,MEDICAL,NaN,6,23M,100+,Free,0,Everyone,Medical,"July 20, 2018",1.3.5,5.0 and up
5147,Maricopa AH,MEDICAL,NaN,0,29M,100+,Free,0,Everyone,Medical,"July 16, 2018",300000.1.11,4.0.3 and up
6598,Free Blood Pressure,MEDICAL,NaN,7,5.7M,"5,000+",Free,0,Everyone,Medical,"October 13, 2016",3.0.0,4.0.3 and up

In [107]:
duplicate

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
229,Quick PDF Scanner + OCR FREE,BUSINESS,4.2,80805,Varies with device,"5,000,000+",Free,0,Everyone,Business,"February 26, 2018",Varies with device,4.0.3 and up
236,Box,BUSINESS,4.2,159872,Varies with device,"10,000,000+",Free,0,Everyone,Business,"July 31, 2018",Varies with device,Varies with device
239,Google My Business,BUSINESS,4.4,70991,Varies with device,"5,000,000+",Free,0,Everyone,Business,"July 24, 2018",2.19.0.204537701,4.4 and up
256,ZOOM Cloud Meetings,BUSINESS,4.4,31614,37M,"10,000,000+",Free,0,Everyone,Business,"July 20, 2018",4.1.28165.0716,4.0 and up
261,join.me - Simple Meetings,BUSINESS,4.0,6989,Varies with device,"1,000,000+",Free,0,Everyone,Business,"July 16, 2018",4.3.0.508,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8643,Wunderlist: To-Do List & Tasks,PRODUCTIVITY,4.6,404610,Varies with device,"10,000,000+",Free,0,Everyone,Productivity,"April 6, 2018",Varies with device,Varies with device
8654,"TickTick: To Do List with Reminder, Day Planner",PRODUCTIVITY,4.6,25370,Varies with device,"1,000,000+",Free,0,Everyone,Productivity,"August 6, 2018",Varies with device,Varies with device
8658,ColorNote Notepad Notes,PRODUCTIVITY,4.6,2401017,Varies with device,"100,000,000+",Free,0,Everyone,Productivity,"June 27, 2018",Varies with device,Varies with device
10049,Airway Ex - Intubate. Anesthetize. Train.,MEDICAL,4.3,123,86M,"10,000+",Free,0,Everyone,Medical,"June 1, 2018",0.6.88,5.0 and up
10768,AAFP,MEDICAL,3.8,63,24M,"10,000+",Free,0,Everyone,Medical,"June 22, 2018",2.3.1,5.0 and up

In [116]:
df=df.drop_duplicates()

In [117]:
df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [120]:
df=df.dropna(subset=["Rating","Current Ver","Android Ver"])

In [4]:
df[df["Size"]=="Varies with device"]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
37,Floor Plan Creator,ART_AND_DESIGN,4.1,36639,Varies with device,"5,000,000+",Free,0,Everyone,Art & Design,"July 14, 2018",Varies with device,2.3.3 and up
42,Textgram - write on photos,ART_AND_DESIGN,4.4,295221,Varies with device,"10,000,000+",Free,0,Everyone,Art & Design,"July 30, 2018",Varies with device,Varies with device
52,Used Cars and Trucks for Sale,AUTO_AND_VEHICLES,4.6,17057,Varies with device,"1,000,000+",Free,0,Everyone,Auto & Vehicles,"July 30, 2018",Varies with device,Varies with device
67,Ulysse Speedometer,AUTO_AND_VEHICLES,4.3,40211,Varies with device,"5,000,000+",Free,0,Everyone,Auto & Vehicles,"July 30, 2018",Varies with device,Varies with device
68,REPUVE,AUTO_AND_VEHICLES,3.9,356,Varies with device,"100,000+",Free,0,Everyone,Auto & Vehicles,"May 25, 2018",Varies with device,Varies with device
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10713,My Earthquake Alerts - US & Worldwide Earthquakes,WEATHER,4.4,3471,Varies with device,"100,000+",Free,0,Everyone,Weather,"July 24, 2018",Varies with device,Varies with device
10725,Posta App,MAPS_AND_NAVIGATION,3.6,8,Varies with device,"1,000+",Free,0,Everyone,Maps & Navigation,"September 27, 2017",Varies with device,4.4 and up
10765,Chat For Strangers - Video Chat,SOCIAL,3.4,622,Varies with device,"100,000+",Free,0,Mature 17+,Social,"May 23, 2018",Varies with device,Varies with device
10826,Frim: get new friends on local chat rooms,SOCIAL,4.0,88486,Varies with device,"5,000,000+",Free,0,Mature 17+,Social,"March 23, 2018",Varies with device,Varies with device
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device

In [121]:
df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10834,FR Calculator,FAMILY,4.0,7,2.6M,500+,Free,0,Everyone,Education,"June 18, 2017",1.0.0,4.1 and up
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1,4.1 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [122]:
df.dtypes

App                object
Category           object
Rating            float64
Reviews            object
Size               object
Installs           object
Type               object
Price              object
Content Rating     object
Genres             object
Last Updated       object
Current Ver        object
Android Ver        object
dtype: object

In [123]:
df["Installs"]=df["Installs"].str.replace("+","")

C:\Users\INTERN\AppData\Local\Temp\ipykernel_6668\304575038.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Installs"]=df["Installs"].str.replace("+","")

In [124]:
df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10834,FR Calculator,FAMILY,4.0,7,2.6M,500,Free,0,Everyone,Education,"June 18, 2017",1.0.0,4.1 and up
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100,Free,0,Everyone,Education,"July 6, 2018",1,4.1 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [125]:
df["Installs"]=df["Installs"].str.replace(",","")

C:\Users\INTERN\AppData\Local\Temp\ipykernel_6668\3325231461.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Installs"]=df["Installs"].str.replace(",","")

In [126]:
df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,10000,Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,500000,Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,5000000,Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,50000000,Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,100000,Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10834,FR Calculator,FAMILY,4.0,7,2.6M,500,Free,0,Everyone,Education,"June 18, 2017",1.0.0,4.1 and up
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,5000,Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100,Free,0,Everyone,Education,"July 6, 2018",1,4.1 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,1000,Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,10000000,Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [128]:
df["Installs"]=df["Installs"].astype(int)

C:\Users\INTERN\AppData\Local\Temp\ipykernel_6668\532186509.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Installs"]=df["Installs"].astype(int)

In [129]:
df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,10000,Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,500000,Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,5000000,Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,50000000,Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,100000,Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10834,FR Calculator,FAMILY,4.0,7,2.6M,500,Free,0,Everyone,Education,"June 18, 2017",1.0.0,4.1 and up
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,5000,Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100,Free,0,Everyone,Education,"July 6, 2018",1,4.1 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,1000,Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,10000000,Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [130]:
df.max()

App               🔥 Football Wallpapers 4K | Full HD Backgrounds 😍
Category                                                   WEATHER
Rating                                                         5.0
Reviews                                                       9992
Size                                            Varies with device
Installs                                                1000000000
Type                                                          Paid
Price                                                            0
Content Rating                                             Unrated
Genres                                                        Word
Last Updated                                     September 9, 2016
Current Ver                                          version 0.994
Android Ver                                     Varies with device
dtype: object

In [131]:
df.min()

App               +Download 4 Instagram Twitter
Category                         ART_AND_DESIGN
Rating                                      1.0
Reviews                                       1
Size                                       1.0M
Installs                                      1
Type                                       Free
Price                                     $0.99
Content Rating                  Adults only 18+
Genres                                   Action
Last Updated                      April 1, 2016
Current Ver                             0.0.0.2
Android Ver                          1.0 and up
dtype: object

In [132]:
df["Installs"].mean()

np.float64(16500606.047490435)

In [133]:
df["Rating"].mean()

np.float64(4.187958586540625)

In [145]:
df["Category"].unique()

array(['ART_AND_DESIGN', 'AUTO_AND_VEHICLES', 'BEAUTY',
       'BOOKS_AND_REFERENCE', 'BUSINESS', 'COMICS', 'COMMUNICATION',
       'DATING', 'EDUCATION', 'ENTERTAINMENT', 'EVENTS', 'FINANCE',
       'FOOD_AND_DRINK', 'HEALTH_AND_FITNESS', 'HOUSE_AND_HOME',
       'LIBRARIES_AND_DEMO', 'LIFESTYLE', 'GAME', 'FAMILY', 'MEDICAL',
       'SOCIAL', 'SHOPPING', 'PHOTOGRAPHY', 'SPORTS', 'TRAVEL_AND_LOCAL',
       'TOOLS', 'PERSONALIZATION', 'PRODUCTIVITY', 'PARENTING', 'WEATHER',
       'VIDEO_PLAYERS', 'NEWS_AND_MAGAZINES', 'MAPS_AND_NAVIGATION'],
      dtype=object)

In [146]:
df["Content Rating"].unique()

array(['Everyone', 'Teen', 'Everyone 10+', 'Mature 17+',
       'Adults only 18+', 'Unrated'], dtype=object)

In [147]:
df["Genres"].unique()

array(['Art & Design', 'Art & Design;Pretend Play',
       'Art & Design;Creativity', 'Auto & Vehicles', 'Beauty',
       'Books & Reference', 'Business', 'Comics', 'Comics;Creativity',
       'Communication', 'Dating', 'Education;Education', 'Education',
       'Education;Creativity', 'Education;Music & Video',
       'Education;Action & Adventure', 'Education;Pretend Play',
       'Education;Brain Games', 'Entertainment',
       'Entertainment;Music & Video', 'Entertainment;Brain Games',
       'Entertainment;Creativity', 'Events', 'Finance', 'Food & Drink',
       'Health & Fitness', 'House & Home', 'Libraries & Demo',
       'Lifestyle', 'Lifestyle;Pretend Play',
       'Adventure;Action & Adventure', 'Arcade', 'Casual', 'Card',
       'Casual;Pretend Play', 'Action', 'Strategy', 'Puzzle', 'Sports',
       'Music', 'Word', 'Racing', 'Casual;Creativity',
       'Casual;Action & Adventure', 'Simulation', 'Adventure', 'Board',
       'Trivia', 'Role Playing', 'Simulation;Education',
       'Action;Action & Adventure', 'Casual;Brain Games',
       'Simulation;Action & Adventure', 'Educational;Creativity',
       'Puzzle;Brain Games', 'Educational;Education', 'Card;Brain Games',
       'Educational;Brain Games', 'Educational;Pretend Play',
       'Entertainment;Education', 'Casual;Education',
       'Music;Music & Video', 'Racing;Action & Adventure',
       'Arcade;Pretend Play', 'Role Playing;Action & Adventure',
       'Simulation;Pretend Play', 'Puzzle;Creativity',
       'Sports;Action & Adventure', 'Educational;Action & Adventure',
       'Arcade;Action & Adventure', 'Entertainment;Action & Adventure',
       'Puzzle;Action & Adventure', 'Strategy;Action & Adventure',
       'Music & Audio;Music & Video', 'Health & Fitness;Education',
       'Adventure;Education', 'Board;Brain Games',
       'Board;Action & Adventure', 'Board;Pretend Play',
       'Casual;Music & Video', 'Role Playing;Pretend Play',
       'Entertainment;Pretend Play', 'Video Players & Editors;Creativity',
       'Card;Action & Adventure', 'Medical', 'Social', 'Shopping',
       'Photography', 'Travel & Local',
       'Travel & Local;Action & Adventure', 'Tools', 'Tools;Education',
       'Personalization', 'Productivity', 'Parenting',
       'Parenting;Music & Video', 'Parenting;Brain Games',
       'Parenting;Education', 'Weather', 'Video Players & Editors',
       'Video Players & Editors;Music & Video', 'News & Magazines',
       'Maps & Navigation', 'Health & Fitness;Action & Adventure',
       'Educational', 'Casino', 'Adventure;Brain Games',
       'Lifestyle;Education', 'Books & Reference;Education',
       'Puzzle;Education', 'Role Playing;Brain Games',
       'Strategy;Education', 'Racing;Pretend Play',
       'Communication;Creativity', 'Strategy;Creativity'], dtype=object)

In [148]:
df["Last Updated"].unique()

array(['January 7, 2018', 'January 15, 2018', 'August 1, 2018', ...,
       'January 20, 2014', 'February 16, 2014', 'March 23, 2014'],
      shape=(1299,), dtype=object)

In [149]:
df.dtypes

App                object
Category           object
Rating            float64
Reviews            object
Size               object
Installs            int64
Type               object
Price              object
Content Rating     object
Genres             object
Last Updated       object
Current Ver        object
Android Ver        object
dtype: object

In [150]:
df["Current Ver"].unique()

array(['1.0.0', '2.0.0', '1.2.4', ..., '1.5.447', '1.0.612928', '0.3.4'],
      shape=(2594,), dtype=object)

In [151]:
df["Android Ver"].unique()

array(['4.0.3 and up', '4.2 and up', '4.4 and up', '2.3 and up',
       '3.0 and up', '4.1 and up', '4.0 and up', '2.3.3 and up',
       'Varies with device', '2.2 and up', '5.0 and up', '6.0 and up',
       '1.6 and up', '1.5 and up', '2.1 and up', '7.0 and up',
       '4.3 and up', '4.0.3 - 7.1.1', '2.0 and up', '3.2 and up',
       '4.4W and up', '5.1 and up', '7.1 and up', '7.0 - 7.1.1',
       '8.0 and up', '5.0 - 8.0', '3.1 and up', '2.0.1 and up',
       '4.1 - 7.1.1', '5.0 - 6.0', '1.0 and up'], dtype=object)

In [153]:
df["Size"].unique()

array(['19M', '14M', '8.7M', '25M', '2.8M', '5.6M', '29M', '33M', '3.1M',
       '28M', '12M', '20M', '21M', '37M', '5.5M', '17M', '39M', '31M',
       '4.2M', '23M', '6.0M', '6.1M', '4.6M', '9.2M', '5.2M', '11M',
       '24M', 'Varies with device', '9.4M', '15M', '10M', '1.2M', '26M',
       '8.0M', '7.9M', '56M', '57M', '35M', '54M', '201k', '3.6M', '5.7M',
       '8.6M', '2.4M', '27M', '2.7M', '2.5M', '7.0M', '16M', '3.4M',
       '8.9M', '3.9M', '2.9M', '38M', '32M', '5.4M', '18M', '1.1M',
       '2.2M', '4.5M', '9.8M', '52M', '9.0M', '6.7M', '30M', '2.6M',
       '7.1M', '22M', '6.4M', '3.2M', '8.2M', '4.9M', '9.5M', '5.0M',
       '5.9M', '13M', '73M', '6.8M', '3.5M', '4.0M', '2.3M', '2.1M',
       '42M', '9.1M', '55M', '23k', '7.3M', '6.5M', '1.5M', '7.5M', '51M',
       '41M', '48M', '8.5M', '46M', '8.3M', '4.3M', '4.7M', '3.3M', '40M',
       '7.8M', '8.8M', '6.6M', '5.1M', '61M', '66M', '79k', '8.4M',
       '3.7M', '118k', '44M', '695k', '1.6M', '6.2M', '53M', '1.4M',
       '3.0M', '7.2M', '5.8M', '3.8M', '9.6M', '45M', '63M', '49M', '77M',
       '4.4M', '70M', '9.3M', '8.1M', '36M', '6.9M', '7.4M', '84M', '97M',
       '2.0M', '1.9M', '1.8M', '5.3M', '47M', '556k', '526k', '76M',
       '7.6M', '59M', '9.7M', '78M', '72M', '43M', '7.7M', '6.3M', '334k',
       '93M', '65M', '79M', '100M', '58M', '50M', '68M', '64M', '34M',
       '67M', '60M', '94M', '9.9M', '232k', '99M', '624k', '95M', '8.5k',
       '41k', '292k', '80M', '1.7M', '10.0M', '74M', '62M', '69M', '75M',
       '98M', '85M', '82M', '96M', '87M', '71M', '86M', '91M', '81M',
       '92M', '83M', '88M', '704k', '862k', '899k', '378k', '4.8M',
       '266k', '375k', '1.3M', '975k', '980k', '4.1M', '89M', '696k',
       '544k', '525k', '920k', '779k', '853k', '720k', '713k', '772k',
       '318k', '58k', '241k', '196k', '857k', '51k', '953k', '865k',
       '251k', '930k', '540k', '313k', '746k', '203k', '26k', '314k',
       '239k', '371k', '220k', '730k', '756k', '91k', '293k', '17k',
       '74k', '14k', '317k', '78k', '924k', '818k', '81k', '939k', '169k',
       '45k', '965k', '90M', '545k', '61k', '283k', '655k', '714k', '93k',
       '872k', '121k', '322k', '976k', '206k', '954k', '444k', '717k',
       '210k', '609k', '308k', '306k', '175k', '350k', '383k', '454k',
       '1.0M', '70k', '812k', '442k', '842k', '417k', '412k', '459k',
       '478k', '335k', '782k', '721k', '430k', '429k', '192k', '460k',
       '728k', '496k', '816k', '414k', '506k', '887k', '613k', '778k',
       '683k', '592k', '186k', '840k', '647k', '373k', '437k', '598k',
       '716k', '585k', '982k', '219k', '55k', '323k', '691k', '511k',
       '951k', '963k', '25k', '554k', '351k', '27k', '82k', '208k',
       '551k', '29k', '103k', '116k', '153k', '209k', '499k', '173k',
       '597k', '809k', '122k', '411k', '400k', '801k', '787k', '50k',
       '643k', '986k', '516k', '837k', '780k', '20k', '498k', '600k',
       '656k', '221k', '228k', '176k', '34k', '259k', '164k', '458k',
       '629k', '28k', '288k', '775k', '785k', '636k', '916k', '994k',
       '309k', '485k', '914k', '903k', '608k', '500k', '54k', '562k',
       '847k', '948k', '811k', '270k', '48k', '523k', '784k', '280k',
       '24k', '892k', '154k', '18k', '33k', '860k', '364k', '387k',
       '626k', '161k', '879k', '39k', '170k', '141k', '160k', '144k',
       '143k', '190k', '376k', '193k', '473k', '246k', '73k', '253k',
       '957k', '420k', '72k', '404k', '470k', '226k', '240k', '89k',
       '234k', '257k', '861k', '467k', '676k', '552k', '582k', '619k'],
      dtype=object)

In [6]:
import pandas as pd
import numpy as np

def convert_size(size):
    if size == 'Varies with device':
        return float(0)
    elif 'M' in size:
        return float(size.replace('M', '')) * 1024
    elif 'k' in size:
        return float(size.replace('k', ''))
    else:
        return np.nan

df['Size_KB'] = df['Size'].apply(convert_size)

In [8]:
df['Size_KB']

0        19456.0
1        14336.0
2         8908.8
3        25600.0
4         2867.2
          ...
10836    54272.0
10837     3686.4
10838     9728.0
10839        0.0
10840    19456.0
Name: Size_KB, Length: 10841, dtype: float64

In [9]:
df["Size_KB"].unique()

array([1.94560e+04, 1.43360e+04, 8.90880e+03, 2.56000e+04, 2.86720e+03,
       5.73440e+03, 2.96960e+04, 3.37920e+04, 3.17440e+03, 2.86720e+04,
       1.22880e+04, 2.04800e+04, 2.15040e+04, 3.78880e+04, 2.76480e+03,
       5.63200e+03, 1.74080e+04, 3.99360e+04, 3.17440e+04, 4.30080e+03,
       7.16800e+03, 2.35520e+04, 6.14400e+03, 6.24640e+03, 4.71040e+03,
       9.42080e+03, 5.32480e+03, 1.12640e+04, 2.45760e+04, 0.00000e+00,
       9.62560e+03, 1.53600e+04, 1.02400e+04, 1.22880e+03, 2.66240e+04,
       8.19200e+03, 8.08960e+03, 5.73440e+04, 5.83680e+04, 3.58400e+04,
       5.52960e+04, 2.01000e+02, 3.68640e+03, 5.83680e+03, 8.80640e+03,
       2.45760e+03, 2.76480e+04, 2.56000e+03, 1.63840e+04, 3.48160e+03,
       9.11360e+03, 3.99360e+03, 2.96960e+03, 3.89120e+04, 3.27680e+04,
       5.52960e+03, 1.84320e+04, 1.12640e+03, 2.25280e+03, 4.60800e+03,
       1.00352e+04, 5.32480e+04, 9.21600e+03, 6.86080e+03, 3.07200e+04,
       2.66240e+03, 7.27040e+03, 3.78880e+03, 2.25280e+04, 7.57760e+03,
       6.55360e+03, 3.27680e+03, 8.39680e+03, 1.01376e+04, 5.01760e+03,
       9.72800e+03, 5.12000e+03, 6.04160e+03, 1.33120e+04, 7.47520e+04,
       6.96320e+03, 3.58400e+03, 4.09600e+03, 2.35520e+03, 7.37280e+03,
       2.15040e+03, 4.30080e+04, 7.47520e+03, 9.31840e+03, 5.63200e+04,
       2.30000e+01, 6.65600e+03, 1.53600e+03, 7.68000e+03, 5.22240e+04,
       4.19840e+04, 4.91520e+04, 8.70400e+03, 4.71040e+04, 8.49920e+03,
       4.40320e+03, 4.81280e+03, 3.37920e+03, 4.09600e+04, 7.98720e+03,
       9.01120e+03, 6.75840e+03, 5.22240e+03, 6.24640e+04, 6.75840e+04,
       7.90000e+01, 8.60160e+03, 1.18000e+02, 4.50560e+04, 6.95000e+02,
       1.63840e+03, 6.34880e+03, 1.80000e+01, 5.42720e+04, 1.43360e+03,
       3.07200e+03, 5.93920e+03, 3.89120e+03, 9.83040e+03, 4.60800e+04,
       6.45120e+04, 5.01760e+04, 7.88480e+04, 4.50560e+03, 4.91520e+03,
       7.16800e+04, 7.06560e+03, 9.52320e+03, 8.29440e+03, 3.68640e+04,
       8.60160e+04, 9.93280e+04, 2.04800e+03, 1.94560e+03, 1.84320e+03,
       5.42720e+03, 4.81280e+04, 5.56000e+02, 5.26000e+02, 7.78240e+04,
       7.78240e+03, 6.04160e+04, 9.93280e+03, 7.98720e+04, 7.37280e+04,
       4.40320e+04, 7.88480e+03, 6.45120e+03, 3.34000e+02, 3.48160e+04,
       9.52320e+04, 6.65600e+04, 8.08960e+04, 1.02400e+05, 5.93920e+04,
       5.12000e+04, 6.96320e+04, 6.55360e+04, 6.86080e+04, 6.14400e+04,
       9.62560e+04, 2.32000e+02, 1.01376e+05, 6.24000e+02, 9.72800e+04,
       8.50000e+00, 4.10000e+01, 2.92000e+02, 1.10000e+01, 8.19200e+04,
       1.74080e+03, 7.57760e+04, 6.34880e+04, 7.06560e+04, 7.68000e+04,
       1.00352e+05, 8.70400e+04, 8.39680e+04, 9.83040e+04, 8.90880e+04,
       7.27040e+04, 8.80640e+04, 9.31840e+04, 8.29440e+04, 9.42080e+04,
       8.49920e+04, 9.01120e+04, 7.04000e+02, 8.62000e+02, 8.99000e+02,
       3.78000e+02, 2.66000e+02, 3.75000e+02, 1.33120e+03, 9.75000e+02,
       9.80000e+02, 4.19840e+03, 9.11360e+04, 6.96000e+02, 5.44000e+02,
       5.25000e+02, 9.20000e+02, 7.79000e+02, 8.53000e+02, 7.20000e+02,
       7.13000e+02, 7.72000e+02, 3.18000e+02, 5.80000e+01, 2.41000e+02,
       1.96000e+02, 8.57000e+02, 5.10000e+01, 9.53000e+02, 8.65000e+02,
       2.51000e+02, 9.30000e+02, 5.40000e+02, 3.13000e+02, 7.46000e+02,
       2.03000e+02, 2.60000e+01, 3.14000e+02, 2.39000e+02, 3.71000e+02,
       2.20000e+02, 7.30000e+02, 7.56000e+02, 9.10000e+01, 2.93000e+02,
       1.70000e+01, 7.40000e+01, 1.40000e+01, 3.17000e+02, 7.80000e+01,
       9.24000e+02, 9.02000e+02, 8.18000e+02, 8.10000e+01, 9.39000e+02,
       1.69000e+02, 4.50000e+01, 4.75000e+02, 9.65000e+02, 9.21600e+04,
       5.45000e+02, 6.10000e+01, 2.83000e+02, 6.55000e+02, 7.14000e+02,
       9.30000e+01, 8.72000e+02, 1.21000e+02, 3.22000e+02, 1.02400e+03,
       9.76000e+02, 1.72000e+02, 2.38000e+02, 5.49000e+02, 2.06000e+02,
       9.54000e+02, 4.44000e+02, 7.17000e+02, 2.10000e+02, 6.09000e+02,
       3.08000e+02, 7.05000e+02, 3.06000e+02, 9.04000e+02, 4.73000e+02,
       1.75000e+02, 3.50000e+02, 3.83000e+02, 4.54000e+02, 4.21000e+02,
       7.00000e+01, 8.12000e+02, 4.42000e+02, 8.42000e+02, 4.17000e+02,
       4.12000e+02, 4.59000e+02, 4.78000e+02, 3.35000e+02, 7.82000e+02,
       7.21000e+02, 4.30000e+02, 4.29000e+02, 1.92000e+02, 2.00000e+02,
       4.60000e+02, 7.28000e+02, 4.96000e+02, 8.16000e+02, 4.14000e+02,
       5.06000e+02, 8.87000e+02, 6.13000e+02, 2.43000e+02, 5.69000e+02,
       7.78000e+02, 6.83000e+02, 5.92000e+02, 3.19000e+02, 1.86000e+02,
       8.40000e+02, 6.47000e+02, 1.91000e+02, 3.73000e+02, 4.37000e+02,
       5.98000e+02, 7.16000e+02, 5.85000e+02, 9.82000e+02, 2.22000e+02,
       2.19000e+02, 5.50000e+01, 9.48000e+02, 3.23000e+02, 6.91000e+02,
       5.11000e+02, 9.51000e+02, 9.63000e+02, 2.50000e+01, 5.54000e+02,
       3.51000e+02, 2.70000e+01, 8.20000e+01, 2.08000e+02, 9.13000e+02,
       5.14000e+02, 5.51000e+02, 2.90000e+01, 1.03000e+02, 8.98000e+02,
       7.43000e+02, 1.16000e+02, 1.53000e+02, 2.09000e+02, 3.53000e+02,
       4.99000e+02, 1.73000e+02, 5.97000e+02, 8.09000e+02, 1.22000e+02,
       4.11000e+02, 4.00000e+02, 8.01000e+02, 7.87000e+02, 2.37000e+02,
       5.00000e+01, 6.43000e+02, 9.86000e+02, 9.70000e+01, 5.16000e+02,
       8.37000e+02, 7.80000e+02, 9.61000e+02, 2.69000e+02, 2.00000e+01,
       4.98000e+02, 6.00000e+02, 7.49000e+02, 6.42000e+02, 8.81000e+02,
       7.20000e+01, 6.56000e+02, 6.01000e+02, 2.21000e+02, 2.28000e+02,
       1.08000e+02, 9.40000e+02, 1.76000e+02, 3.30000e+01, 6.63000e+02,
       3.40000e+01, 9.42000e+02, 2.59000e+02, 1.64000e+02, 4.58000e+02,
       2.45000e+02, 6.29000e+02, 2.80000e+01, 2.88000e+02, 7.75000e+02,
       7.85000e+02, 6.36000e+02, 9.16000e+02, 9.94000e+02, 3.09000e+02,
       4.85000e+02, 9.14000e+02, 9.03000e+02, 6.08000e+02, 5.00000e+02,
       5.40000e+01, 5.62000e+02, 8.47000e+02, 9.57000e+02, 6.88000e+02,
       8.11000e+02, 2.70000e+02, 4.80000e+01, 3.29000e+02, 5.23000e+02,
       9.21000e+02, 8.74000e+02, 9.81000e+02, 7.84000e+02, 2.80000e+02,
       2.40000e+01, 5.18000e+02, 7.54000e+02, 8.92000e+02, 1.54000e+02,
       8.60000e+02, 3.64000e+02, 3.87000e+02, 6.26000e+02, 1.61000e+02,
       8.79000e+02, 3.90000e+01, 9.70000e+02, 1.70000e+02, 1.41000e+02,
       1.60000e+02, 1.44000e+02, 1.43000e+02, 1.90000e+02, 3.76000e+02,
       1.93000e+02, 2.46000e+02, 7.30000e+01, 6.58000e+02, 9.92000e+02,
       2.53000e+02, 4.20000e+02, 4.04000e+02,         nan, 4.70000e+02,
       2.26000e+02, 2.40000e+02, 8.90000e+01, 2.34000e+02, 2.57000e+02,
       8.61000e+02, 4.67000e+02, 1.57000e+02, 4.40000e+01, 6.76000e+02,
       6.70000e+01, 5.52000e+02, 8.85000e+02, 1.02000e+03, 5.82000e+02,
       6.19000e+02])

In [10]:
df["Size_KB"]

0        19456.0
1        14336.0
2         8908.8
3        25600.0
4         2867.2
          ...
10836    54272.0
10837     3686.4
10838     9728.0
10839        0.0
10840    19456.0
Name: Size_KB, Length: 10841, dtype: float64

In [11]:
df["Size_KB"].isnull().sum()

np.int64(1)

In [12]:
df["Size_KB"]=df["Size_KB"].fillna(0)

In [13]:
df["Size_KB"]

0        19456.0
1        14336.0
2         8908.8
3        25600.0
4         2867.2
          ...
10836    54272.0
10837     3686.4
10838     9728.0
10839        0.0
10840    19456.0
Name: Size_KB, Length: 10841, dtype: float64

In [14]:
df["Size_KB"].unique()

array([1.94560e+04, 1.43360e+04, 8.90880e+03, 2.56000e+04, 2.86720e+03,
       5.73440e+03, 2.96960e+04, 3.37920e+04, 3.17440e+03, 2.86720e+04,
       1.22880e+04, 2.04800e+04, 2.15040e+04, 3.78880e+04, 2.76480e+03,
       5.63200e+03, 1.74080e+04, 3.99360e+04, 3.17440e+04, 4.30080e+03,
       7.16800e+03, 2.35520e+04, 6.14400e+03, 6.24640e+03, 4.71040e+03,
       9.42080e+03, 5.32480e+03, 1.12640e+04, 2.45760e+04, 0.00000e+00,
       9.62560e+03, 1.53600e+04, 1.02400e+04, 1.22880e+03, 2.66240e+04,
       8.19200e+03, 8.08960e+03, 5.73440e+04, 5.83680e+04, 3.58400e+04,
       5.52960e+04, 2.01000e+02, 3.68640e+03, 5.83680e+03, 8.80640e+03,
       2.45760e+03, 2.76480e+04, 2.56000e+03, 1.63840e+04, 3.48160e+03,
       9.11360e+03, 3.99360e+03, 2.96960e+03, 3.89120e+04, 3.27680e+04,
       5.52960e+03, 1.84320e+04, 1.12640e+03, 2.25280e+03, 4.60800e+03,
       1.00352e+04, 5.32480e+04, 9.21600e+03, 6.86080e+03, 3.07200e+04,
       2.66240e+03, 7.27040e+03, 3.78880e+03, 2.25280e+04, 7.57760e+03,
       6.55360e+03, 3.27680e+03, 8.39680e+03, 1.01376e+04, 5.01760e+03,
       9.72800e+03, 5.12000e+03, 6.04160e+03, 1.33120e+04, 7.47520e+04,
       6.96320e+03, 3.58400e+03, 4.09600e+03, 2.35520e+03, 7.37280e+03,
       2.15040e+03, 4.30080e+04, 7.47520e+03, 9.31840e+03, 5.63200e+04,
       2.30000e+01, 6.65600e+03, 1.53600e+03, 7.68000e+03, 5.22240e+04,
       4.19840e+04, 4.91520e+04, 8.70400e+03, 4.71040e+04, 8.49920e+03,
       4.40320e+03, 4.81280e+03, 3.37920e+03, 4.09600e+04, 7.98720e+03,
       9.01120e+03, 6.75840e+03, 5.22240e+03, 6.24640e+04, 6.75840e+04,
       7.90000e+01, 8.60160e+03, 1.18000e+02, 4.50560e+04, 6.95000e+02,
       1.63840e+03, 6.34880e+03, 1.80000e+01, 5.42720e+04, 1.43360e+03,
       3.07200e+03, 5.93920e+03, 3.89120e+03, 9.83040e+03, 4.60800e+04,
       6.45120e+04, 5.01760e+04, 7.88480e+04, 4.50560e+03, 4.91520e+03,
       7.16800e+04, 7.06560e+03, 9.52320e+03, 8.29440e+03, 3.68640e+04,
       8.60160e+04, 9.93280e+04, 2.04800e+03, 1.94560e+03, 1.84320e+03,
       5.42720e+03, 4.81280e+04, 5.56000e+02, 5.26000e+02, 7.78240e+04,
       7.78240e+03, 6.04160e+04, 9.93280e+03, 7.98720e+04, 7.37280e+04,
       4.40320e+04, 7.88480e+03, 6.45120e+03, 3.34000e+02, 3.48160e+04,
       9.52320e+04, 6.65600e+04, 8.08960e+04, 1.02400e+05, 5.93920e+04,
       5.12000e+04, 6.96320e+04, 6.55360e+04, 6.86080e+04, 6.14400e+04,
       9.62560e+04, 2.32000e+02, 1.01376e+05, 6.24000e+02, 9.72800e+04,
       8.50000e+00, 4.10000e+01, 2.92000e+02, 1.10000e+01, 8.19200e+04,
       1.74080e+03, 7.57760e+04, 6.34880e+04, 7.06560e+04, 7.68000e+04,
       1.00352e+05, 8.70400e+04, 8.39680e+04, 9.83040e+04, 8.90880e+04,
       7.27040e+04, 8.80640e+04, 9.31840e+04, 8.29440e+04, 9.42080e+04,
       8.49920e+04, 9.01120e+04, 7.04000e+02, 8.62000e+02, 8.99000e+02,
       3.78000e+02, 2.66000e+02, 3.75000e+02, 1.33120e+03, 9.75000e+02,
       9.80000e+02, 4.19840e+03, 9.11360e+04, 6.96000e+02, 5.44000e+02,
       5.25000e+02, 9.20000e+02, 7.79000e+02, 8.53000e+02, 7.20000e+02,
       7.13000e+02, 7.72000e+02, 3.18000e+02, 5.80000e+01, 2.41000e+02,
       1.96000e+02, 8.57000e+02, 5.10000e+01, 9.53000e+02, 8.65000e+02,
       2.51000e+02, 9.30000e+02, 5.40000e+02, 3.13000e+02, 7.46000e+02,
       2.03000e+02, 2.60000e+01, 3.14000e+02, 2.39000e+02, 3.71000e+02,
       2.20000e+02, 7.30000e+02, 7.56000e+02, 9.10000e+01, 2.93000e+02,
       1.70000e+01, 7.40000e+01, 1.40000e+01, 3.17000e+02, 7.80000e+01,
       9.24000e+02, 9.02000e+02, 8.18000e+02, 8.10000e+01, 9.39000e+02,
       1.69000e+02, 4.50000e+01, 4.75000e+02, 9.65000e+02, 9.21600e+04,
       5.45000e+02, 6.10000e+01, 2.83000e+02, 6.55000e+02, 7.14000e+02,
       9.30000e+01, 8.72000e+02, 1.21000e+02, 3.22000e+02, 1.02400e+03,
       9.76000e+02, 1.72000e+02, 2.38000e+02, 5.49000e+02, 2.06000e+02,
       9.54000e+02, 4.44000e+02, 7.17000e+02, 2.10000e+02, 6.09000e+02,
       3.08000e+02, 7.05000e+02, 3.06000e+02, 9.04000e+02, 4.73000e+02,
       1.75000e+02, 3.50000e+02, 3.83000e+02, 4.54000e+02, 4.21000e+02,
       7.00000e+01, 8.12000e+02, 4.42000e+02, 8.42000e+02, 4.17000e+02,
       4.12000e+02, 4.59000e+02, 4.78000e+02, 3.35000e+02, 7.82000e+02,
       7.21000e+02, 4.30000e+02, 4.29000e+02, 1.92000e+02, 2.00000e+02,
       4.60000e+02, 7.28000e+02, 4.96000e+02, 8.16000e+02, 4.14000e+02,
       5.06000e+02, 8.87000e+02, 6.13000e+02, 2.43000e+02, 5.69000e+02,
       7.78000e+02, 6.83000e+02, 5.92000e+02, 3.19000e+02, 1.86000e+02,
       8.40000e+02, 6.47000e+02, 1.91000e+02, 3.73000e+02, 4.37000e+02,
       5.98000e+02, 7.16000e+02, 5.85000e+02, 9.82000e+02, 2.22000e+02,
       2.19000e+02, 5.50000e+01, 9.48000e+02, 3.23000e+02, 6.91000e+02,
       5.11000e+02, 9.51000e+02, 9.63000e+02, 2.50000e+01, 5.54000e+02,
       3.51000e+02, 2.70000e+01, 8.20000e+01, 2.08000e+02, 9.13000e+02,
       5.14000e+02, 5.51000e+02, 2.90000e+01, 1.03000e+02, 8.98000e+02,
       7.43000e+02, 1.16000e+02, 1.53000e+02, 2.09000e+02, 3.53000e+02,
       4.99000e+02, 1.73000e+02, 5.97000e+02, 8.09000e+02, 1.22000e+02,
       4.11000e+02, 4.00000e+02, 8.01000e+02, 7.87000e+02, 2.37000e+02,
       5.00000e+01, 6.43000e+02, 9.86000e+02, 9.70000e+01, 5.16000e+02,
       8.37000e+02, 7.80000e+02, 9.61000e+02, 2.69000e+02, 2.00000e+01,
       4.98000e+02, 6.00000e+02, 7.49000e+02, 6.42000e+02, 8.81000e+02,
       7.20000e+01, 6.56000e+02, 6.01000e+02, 2.21000e+02, 2.28000e+02,
       1.08000e+02, 9.40000e+02, 1.76000e+02, 3.30000e+01, 6.63000e+02,
       3.40000e+01, 9.42000e+02, 2.59000e+02, 1.64000e+02, 4.58000e+02,
       2.45000e+02, 6.29000e+02, 2.80000e+01, 2.88000e+02, 7.75000e+02,
       7.85000e+02, 6.36000e+02, 9.16000e+02, 9.94000e+02, 3.09000e+02,
       4.85000e+02, 9.14000e+02, 9.03000e+02, 6.08000e+02, 5.00000e+02,
       5.40000e+01, 5.62000e+02, 8.47000e+02, 9.57000e+02, 6.88000e+02,
       8.11000e+02, 2.70000e+02, 4.80000e+01, 3.29000e+02, 5.23000e+02,
       9.21000e+02, 8.74000e+02, 9.81000e+02, 7.84000e+02, 2.80000e+02,
       2.40000e+01, 5.18000e+02, 7.54000e+02, 8.92000e+02, 1.54000e+02,
       8.60000e+02, 3.64000e+02, 3.87000e+02, 6.26000e+02, 1.61000e+02,
       8.79000e+02, 3.90000e+01, 9.70000e+02, 1.70000e+02, 1.41000e+02,
       1.60000e+02, 1.44000e+02, 1.43000e+02, 1.90000e+02, 3.76000e+02,
       1.93000e+02, 2.46000e+02, 7.30000e+01, 6.58000e+02, 9.92000e+02,
       2.53000e+02, 4.20000e+02, 4.04000e+02, 4.70000e+02, 2.26000e+02,
       2.40000e+02, 8.90000e+01, 2.34000e+02, 2.57000e+02, 8.61000e+02,
       4.67000e+02, 1.57000e+02, 4.40000e+01, 6.76000e+02, 6.70000e+01,
       5.52000e+02, 8.85000e+02, 1.02000e+03, 5.82000e+02, 6.19000e+02])

In [15]:
df["Size_KB"].isnull().sum()

np.int64(0)